import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from '../components/ui/toaster'

const inter = Inter({ subsets: ["latin"] });

import { Plus_Jakarta_Sans } from 'next/font/google'

// Custom Font from Google.
const plusJakartaSansBold = Plus_Jakarta_Sans({
    subsets : ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSansBold.className}>
      <div className="absolute inset-0 -z-10 min-h-max min-w-max items-center [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}