import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from '../components/ui/toaster'

const inter = Inter({ subsets: ["latin"] });

import { Plus_Jakarta_Sans } from 'next/font/google'

// Custom Font from Google.
const plusJakartaSansBold = Plus_Jakarta_Sans({
    subsets : ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSansBold.className} bg-black`}>
      <div className="absolute inset-0 -z-10 h-full w-full bg-black"><div className="absolute inset-0 -z-10 bg-[linear-gradient(to_right,#272727_1px,transparent_1px),linear-gradient(to_bottom,#272727_1px,transparent_1px)] bg-[size:30px_30px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_220%)]"></div>{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
